In [1]:
import torch

In [ ]:


A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

# Using einsum to perform matrix multiplication
C = torch.einsum('ij,jk->ik', A, B)

print(C)

In [ ]:
torch.arange(0, 5)

In [ ]:
torch.arange(0, 5).expand(7, 5)

In [ ]:
trg = torch.tensor([[1,7,4,3,5,9,2,0], [1,5,6,2,4,7,6,2]])
trg

In [ ]:
trg.shape

In [ ]:
trg[:, :-1]

In [3]:
test1 = torch.tril(torch.ones((5, 5)))

In [4]:
test1, test1.shape

(tensor([[1., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0.],
         [1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1.]]),
 torch.Size([5, 5]))

In [7]:
trg_mask = test1.expand(1, 1, 5, 5)
trg_mask, trg_mask.shape

(tensor([[[[1., 0., 0., 0., 0.],
           [1., 1., 0., 0., 0.],
           [1., 1., 1., 0., 0.],
           [1., 1., 1., 1., 0.],
           [1., 1., 1., 1., 1.]]]]),
 torch.Size([1, 1, 5, 5]))

In [8]:
import torch

# Creating a tensor with random integer values
tensor_random_int = torch.randint(low=0, high=10, size=(1, 9, 3))
print(tensor_random_int)

tensor([[[5, 2, 1],
         [1, 9, 0],
         [2, 3, 1],
         [0, 2, 0],
         [5, 1, 3],
         [9, 9, 0],
         [0, 9, 9],
         [2, 7, 7],
         [3, 5, 5]]])


In [9]:
tensor_random_int.shape

torch.Size([1, 9, 3])